Reorganized the project structure, fixed bug in spec running (wrote to project dir).

diff --git a/bin/create_master_repo b/bin/create_master_repo
--- a/bin/create_master_repo
+++ b/bin/create_master_repo
@@ -36,7 +36,7 @@ export GIT_DIR="$dest"
 
 # set up dir/permissions
 umask 002
-mkdir "$dest" || die "Failed to create directory '$dest'"
+mkdir -p "$dest" || die "Failed to create directory '$dest'"
 
 # set up group ownership if group name was given
 if [ "$group" ]; then
